import React, { useEffect, useState } from 'react';
import { ArrowRight, Bot, ChevronRight, Eye, EyeOff, Gamepad2, Landmark, Lock, Mail, Menu, MessageCircle, ShieldCheck, ShoppingBag, Smartphone, User, X, Zap, KeyRound, CreditCard, Fish, TriangleAlert, Headphones, Search, Send } from 'lucide-react';

const topics = [
  { title: 'Phishing Attacks', text: 'Spot deceptive links, urgent messages and fake websites.', icon: Fish, tone: 'blue' },
  { title: 'Social Media Safety', text: 'Protect your accounts and personal information online.', icon: Smartphone, tone: 'green' },
  { title: 'UPI & Banking Safety', text: 'Make every payment with awareness and confidence.', icon: Landmark, tone: 'violet' },
  { title: 'Gaming Scams', text: 'Avoid frauds, fake rewards and in-game scam traps.', icon: Gamepad2, tone: 'amber' },
  { title: 'Email Scams', text: 'Identify suspicious mail before it reaches you.', icon: Mail, tone: 'coral' },
  { title: 'Password Security', text: 'Create strong passwords that keep accounts secure.', icon: KeyRound, tone: 'teal' },
];

const resources = [
  ['Strong Passwords', 'Use long, unique passphrases and a trusted password manager.', KeyRound],
  ['Phishing', 'Pause before clicking links, QR codes, attachments or replying.', Fish],
  ['Safe UPI', 'Never share your UPI PIN or OTP to receive a payment.', CreditCard],
  ['Social Media Safety', 'Turn on privacy controls and two-factor authentication.', Smartphone],
  ['Online Shopping Safety', 'Buy only through verified stores and secure payment pages.', ShoppingBag],
];
const guideContent = {
  'Strong Passwords': ['Use a different password for every account.', 'Make it at least 14 characters long; a memorable passphrase works well.', 'Turn on two-factor authentication wherever it is available.'],
  'Phishing': ['Check the full sender address and website URL before acting.', 'Never open unexpected attachments or shortened links.', 'Verify urgent requests through the organisation’s official website or phone number.'],
  'Safe UPI': ['You never need to enter a UPI PIN to receive money.', 'Do not share OTP, PIN, CVV or screen-sharing access with anyone.', 'If you lose money, call 1930 immediately and save all evidence.'],
  'Social Media Safety': ['Set your profiles to private and review who can contact you.', 'Use a unique password and two-factor authentication.', 'Avoid sharing live location, OTPs, identity documents or personal details.'],
  'Online Shopping Safety': ['Use trusted stores and check the URL begins with https.', 'Avoid deals that look too good to be true.', 'Prefer secure payment methods and retain receipts.'],
  'Phishing Attacks': ['Check the sender and full URL, not just the display name.', 'Avoid links that create urgency or ask for secrets.', 'Report suspicious messages and delete them.'],
  'UPI & Banking Safety': ['Never share your OTP, UPI PIN, card PIN or CVV.', 'To receive money, do not scan QR codes or enter a PIN.', 'Call 1930 promptly if you have been defrauded.'],
  'Gaming Scams': ['Never share game credentials or buy items from unknown sellers.', 'Be wary of free coins, hacks and reward generators.', 'Keep purchases inside the official game or app store.'],
  'Email Scams': ['Check the sender domain and hover over links first.', 'Do not download surprise attachments.', 'Use official sites directly instead of links in messages.'],
  'Password Security': ['Use a unique, long passphrase for each important account.', 'Store passwords in a trusted password manager.', 'Enable two-factor authentication and never share passwords.'],
};

function Logo({ light = false }) { return <a className={`logo ${light ? 'light' : ''}`} href="#/home"><span className="logo-mark"><ShieldCheck size={26}/></span><span><small>STUDENT COMMUNITY</small><strong>CYBER SAFETY</strong><em>HELP DESK</em></span></a> }
function Nav({ page, setMenu }) { const links = [['home','Home'], ['awareness','Awareness'], ['assistant','AI Assistant'], ['report','Report a Scam'], ['resources','Resources'], ['contact','Contact Us']]; return <nav className="nav">{links.map(([id, label]) => <a onClick={()=>setMenu(false)} className={page === id ? 'active' : ''} href={`#/${id}`} key={id}>{label}</a>)}<a className="login-link" href="#/login"><User size={17}/> Login / Sign Up</a></nav> }
function Header({ page }) { const [menu, setMenu] = useState(false); return <header><div className="shell nav-shell"><Logo light/><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu ? <X/>:<Menu/>}</button><div className={menu ? 'nav-open' : ''}><Nav page={page} setMenu={setMenu}/></div></div></header> }
function Hero() { const [query,setQuery]=useState(''); const search=e=>{e.preventDefault();if(query.trim()) window.location.hash=`#/resources?search=${encodeURIComponent(query.trim())}`}; return <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">COMMUNITY</p><h1>CYBER <span>SAFETY</span><br/><i>HELP DESK</i></h1><h2>Stay Safe. Stay Aware.<br/><b>We Are Here to Help.</b></h2><p className="lead">Your student-first space for cyber safety guidance, scam awareness and trusted support.</p><form className="search" onSubmit={search}><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cyber safety resources..."/><button type="submit">Search</button></form><a className="primary" href="#/assistant"><Bot size={20}/> Ask AI Assistant <ArrowRight size={19}/></a><p className="under">Search guides or get instant help from the AI Assistant.</p></div><HeroArt/><aside className="daily-tip"><Zap size={23}/><div><b>Daily Cyber Safety Tip</b><p>Never share your OTP, password or banking PIN with anyone.</p></div></aside></div></section> }
function HeroArt(){ return <div className="hero-art"><div className="glow"></div><div className="monitor"><div className="circuit">⌁ ⌁ ⌁</div><ShieldCheck size={100}/><span>YOUR SAFETY<br/>OUR PRIORITY</span></div><div className="desk"></div><div className="laptop"><Lock/><span></span></div><div className="shield-float"><ShieldCheck size={70}/></div><div className="person"><div></div><i></i></div></div> }
function Topics(){ return <section className="section topics"><div className="shell"><div className="section-head"><p className="eyebrow">LEARN & PROTECT</p><h2>Cyber safety, made <span>simple.</span></h2></div><div className="topic-grid">{topics.map(({title,text,icon:Icon,tone})=><article className="topic-card" key={title}><span className={`round ${tone}`}><Icon/></span><div><h3>{title}</h3><p>{text}</p><a href="#/awareness">Explore <ChevronRight size={15}/></a></div></article>)}</div></div></section> }
function Info(){return <section className="section info"><div className="shell info-grid"><article className="info-card alerts"><div className="card-title"><TriangleAlert/> <h3>Latest Scam Alerts</h3><a href="#/awareness">View all</a></div>{['Fake Internship Messages','QR Code Scam','Fake Scholarship Website','WhatsApp OTP Scam'].map((x,i)=><p key={x}><span>●</span>{x}<time>{[2,5,1,2][i]} {i<2?'hrs':'day'} ago</time></p>)}</article><article className="info-card help"><div className="card-title"><Headphones/> <h3>Need Help?</h3></div><p><span>›</span>Cyber Crime Helpline <b>1930</b></p><p><span>›</span>Report Online Fraud <a href="#/report">Report now</a></p><p><span>›</span>National Cyber Crime Portal <a href="https://cybercrime.gov.in" target="_blank">Visit portal</a></p><p><span>›</span>Emergency Contacts <a href="#/contact">View all</a></p></article><article className="info-card why"><div className="card-title"><ShieldCheck/> <h3>Why Cyber Safety?</h3></div><p>Cyber crimes are increasing every day. Stay informed, alert and protect yourself and others from online frauds and cyber threats.</p><a className="small-btn" href="#/awareness">Learn More</a></article></div></section>}
function Footer(){return <footer><div className="shell footer"><Logo light/><p>© 2026 Student Community Cyber Safety Help Desk.</p><div className="foot-links"><a href="#/privacy">Privacy Policy</a><a href="#/terms">Terms & Conditions</a><a href="#/contact">Contact Support</a></div><div className="social" aria-label="Social media"><b>f</b><b>◎</b><MessageCircle/><b>▶</b></div></div></footer>}
function Home(){return <><Header page="home"/><Hero/><Topics/><Info/><Footer/></>}
function Inner({title,children}){return <><Header/><main className="inner"><div className="shell"><p className="eyebrow">STUDENT CYBER SAFETY HUB</p><h1>{title}</h1>{children}</div></main><Footer/></>}
function Awareness(){return <Inner title="Learn. Recognise. Stay ahead."><p className="page-lead">Short, practical guides to help you recognise risks before they become a problem.</p><div className="resource-grid">{topics.map(({title,text,icon:Icon,tone})=><article className="resource-card" key={title}><span className={`round ${tone}`}><Icon/></span><h3>{title}</h3><p>{text}</p><a className="card-action" href={`#/guide/${encodeURIComponent(title)}`}>Read safety guide <ArrowRight size={16}/></a></article>)}</div></Inner>}
function Resources(){const search=new URLSearchParams(location.hash.split('?')[1]||'').get('search')||'';const shown=resources.filter(([title,text])=>`${title} ${text}`.toLowerCase().includes(search.toLowerCase()));return <Inner title="Your cyber safety toolkit."><p className="page-lead">Save these practical resources and make every digital moment safer.</p>{search&&<p className="search-status">{shown.length ? `Showing ${shown.length} result(s) for “${search}”.` : `No resource found for “${search}”. Try password, phishing, UPI or social media.`}</p>}<div className="resource-grid">{shown.map(([title,text,Icon])=><article className="resource-card" key={title}><span className="round blue"><Icon/></span><h3>{title}</h3><p>{text}</p><a className="card-action" href={`#/guide/${encodeURIComponent(title)}`}>Read resource <ArrowRight size={16}/></a></article>)}</div></Inner>}
function Guide({name}){const clean=decodeURIComponent(name||'');const tips=guideContent[clean]||guideContent.Phishing;return <Inner title={clean || 'Cyber safety guide'}><div className="guide"><p className="page-lead">A quick, practical guide to help you stay protected online.</p><h2>What you should do</h2><ol>{tips.map(tip=><li key={tip}>{tip}</li>)}</ol><div className="callout"><ShieldCheck/> Keep this rule in mind: never share passwords, OTPs, PINs or remote-access permissions.</div><a className="primary" href="#/report">Report a Scam <ArrowRight size={18}/></a></div></Inner>}
function Report(){const [sent,setSent]=useState(false);return <Inner title="Report a scam safely."><div className="form-wrap"><div><h2>Tell us what happened</h2><p>Your details are used only to help guide you towards the right next step. If money was lost, call <b>1930</b> immediately.</p><div className="callout"><Headphones/> Cyber Crime Helpline <strong>1930</strong></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><ShieldCheck size={42}/><h3>Report received</h3><p>Thank you. We will guide you to suitable support resources.</p></div>:<><label>Name<input required placeholder="Your full name"/></label><label>Mobile Number<input required type="tel" placeholder="10-digit mobile number"/></label><label>Scam Type<select required defaultValue=""><option value="" disabled>Select scam type</option><option>UPI / Banking fraud</option><option>Phishing link or call</option><option>Social media scam</option><option>Online shopping scam</option><option>Other</option></select></label><label>Date<input required type="date"/></label><label className="full">Description<textarea required placeholder="Describe what happened, without sharing passwords or OTPs."></textarea></label><button className="primary" type="submit">Submit Report <Send size={18}/></button></>}</form></div></Inner>}
function Assistant(){const [messages,setMessages]=useState([{role:'bot',text:'Hi! I am your Cyber Safety Assistant. Ask me about phishing, passwords, UPI, social media safety, scams, or reporting cybercrime.'}]);const [value,setValue]=useState('');const answer=q=>{const s=q.toLowerCase();if(!/(cyber|scam|phish|password|upi|bank|otp|safe|fraud|email|social|hack|online|security)/.test(s))return 'I can only help with cyber safety and online security questions. Try asking about phishing, passwords, UPI fraud, or reporting a scam.';if(/otp|upi|bank/.test(s))return 'Never share your OTP, UPI PIN, CVV, or screen-sharing access. To receive money, you never need to enter a PIN. If money was lost, call 1930 immediately.';if(/phish|email|link/.test(s))return 'Check the sender, inspect the URL, and do not open unexpected attachments. Genuine organisations do not ask for passwords or OTPs by email.';if(/password/.test(s))return 'Use a unique 14+ character passphrase for every important account and enable two-factor authentication. A password manager makes this much easier.';return 'That is an important cyber-safety concern. Pause before acting, verify through an official channel, and never share passwords, OTPs or banking PINs.'};const submit=e=>{e.preventDefault();if(!value.trim())return;setMessages(m=>[...m,{role:'user',text:value},{role:'bot',text:answer(value)}]);setValue('')};return <Inner title="AI Cyber Safety Assistant"><div className="chat"><div className="chat-top"><Bot/><div><b>Cyber Safety Assistant</b><small><i/> Online · Safety questions only</small></div></div><div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.role==='bot'&&<Bot size={17}/>}<p>{m.text}</p></div>)}</div><form className="chat-form" onSubmit={submit}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Ask a cyber safety question..."/><button aria-label="Send"><Send size={20}/></button></form></div></Inner>}
function Contact(){return <Inner title="We are here to help."><div className="contact-grid"><article><Headphones/><h2>Immediate fraud support</h2><p>If you have lost money to a cyber fraud, call the National Cyber Crime Helpline as soon as possible.</p><strong>1930</strong></article><article><Mail/><h2>Support desk</h2><p>For campus awareness requests or general assistance, write to our community support team.</p><a href="mailto:support@cybersafety.edu">support@cybersafety.edu</a></article></div></Inner>}
function Login(){const [show,setShow]=useState(false);const [mode,setMode]=useState('login');const [notice,setNotice]=useState('');const title=mode==='login'?'Welcome Back!':mode==='register'?'Create your account':'Reset your password';const submit=e=>{e.preventDefault();const data=new FormData(e.currentTarget);if(mode==='forgot'){setNotice(`A password-reset link would be sent to ${data.get('email')}. (Demo mode)`);return}if(mode==='register'){localStorage.setItem('cyberUser',data.get('name'));setNotice('Account created successfully. You can now log in.');setMode('login');return}localStorage.setItem('cyberUser',data.get('email'));window.location.hash='/assistant'};return <main className="login-page"><section className="login-brand"><Logo light/><div className="brand-copy"><p className="eyebrow">STUDENT COMMUNITY</p><h1>Stay Safe. Stay Aware.<br/><span>We Are Here to Help.</span></h1><p>Your trusted platform for cyber safety guidance, awareness and reporting cyber crimes.</p></div><HeroArt/><div className="trust"><span><ShieldCheck/>100% Secure<small>Your data is safe with us.</small></span><span><Bot/>AI Powered<small>Instant answers and support.</small></span><span><User/>Trusted by<small>Students in the community.</small></span></div></section><section className="login-panel"><a className="back" href="#/home">← Back to home</a><div className="login-card"><h1>{title}</h1><p>{mode==='login'?'Login to continue to Cyber Safety Help Desk':mode==='register'?'Join the student cyber safety community.':'Enter your email and we will help you reset your password.'}</p>{notice&&<div className="form-notice">{notice}</div>}<form onSubmit={submit}>{mode==='register'&&<label><User/><input required name="name" placeholder="Full name"/></label>}<label><User/><input required name="email" type="email" placeholder="Email address"/></label>{mode!=='forgot'&&<label><Lock/><input required name="password" type={show?'text':'password'} minLength="6" placeholder="Password"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></label>}{mode==='login'&&<div className="remember"><label><input type="checkbox"/> Remember Me</label><button type="button" className="text-btn" onClick={()=>{setNotice('');setMode('forgot')}}>Forgot Password?</button></div>}<button className="login-btn"> <Lock size={19}/>{mode==='login'?'Login':mode==='register'?'Create Account':'Send Reset Link'}</button></form>{mode==='login'&&<><div className="or"><span/>or<span/></div><button className="create" onClick={()=>{setNotice('');setMode('register')}}><User/> Create New Account</button></>}{mode!=='login'&&<button className="back-login" onClick={()=>{setNotice('');setMode('login')}}>← Back to Login</button>}<div className="safe-box"><ShieldCheck/><b>Together, let’s build a safer<br/>digital community.</b></div></div></section></main>}
function App(){const getRoute=()=>location.hash.slice(2)||'home';const [route,setRoute]=useState(getRoute);useEffect(()=>{const f=()=>setRoute(getRoute());addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const [page,guide]=route.split('?')[0].split('/');const pages={home:<Home/>,awareness:<Awareness/>,assistant:<Assistant/>,report:<Report/>,resources:<Resources/>,contact:<Contact/>,login:<Login/>};return page==='guide'?<Guide name={guide}/>:pages[page]||<Home/>}
export default App;
