import React, { useEffect, useRef, useState } from 'react';
import { ArrowRight, Bot, ChevronRight, Eye, EyeOff, Gamepad2, Landmark, Lock, Mail, Menu, MessageCircle, ShieldCheck, ShoppingBag, Smartphone, User, X, Zap, KeyRound, CreditCard, Fish, TriangleAlert, Headphones, Search, Send, Phone, AlertTriangle, CheckCircle2, Sparkles, TimerReset, FileWarning, LogOut, QrCode, BriefcaseBusiness, IdCard, BadgeAlert } from 'lucide-react';

const topics = [
  { title: 'Phishing Attacks', text: 'Spot deceptive links, urgent messages and fake websites.', icon: Fish, tone: 'blue' },
  { title: 'Social Media Safety', text: 'Protect your accounts and personal information online.', icon: Smartphone, tone: 'green' },
  { title: 'UPI & Banking Safety', text: 'Make every payment with awareness and confidence.', icon: Landmark, tone: 'violet' },
  { title: 'Gaming Scams', text: 'Avoid frauds, fake rewards and in-game scam traps.', icon: Gamepad2, tone: 'amber' },
  { title: 'Email Scams', text: 'Identify suspicious mail before it reaches you.', icon: Mail, tone: 'coral' },
  { title: 'Password Security', text: 'Create strong passwords that keep accounts secure.', icon: KeyRound, tone: 'teal' },
];

const resources = [
  ['Strong Passwords', 'Use long, unique passphrases and a trusted password manager.', KeyRound],
  ['Phishing', 'Pause before clicking links, QR codes, attachments or replying.', Fish],
  ['Safe UPI', 'Never share your UPI PIN or OTP to receive a payment.', CreditCard],
  ['Social Media Safety', 'Turn on privacy controls and two-factor authentication.', Smartphone],
  ['Online Shopping Safety', 'Buy only through verified stores and secure payment pages.', ShoppingBag],
];
const guideContent = {
  'Strong Passwords': ['Use a different password for every account.', 'Make it at least 14 characters long; a memorable passphrase works well.', 'Turn on two-factor authentication wherever it is available.'],
  'Phishing': ['Check the full sender address and website URL before acting.', 'Never open unexpected attachments or shortened links.', 'Verify urgent requests through the organisation’s official website or phone number.'],
  'Safe UPI': ['You never need to enter a UPI PIN to receive money.', 'Do not share OTP, PIN, CVV or screen-sharing access with anyone.', 'If you lose money, call 1930 immediately and save all evidence.'],
  'Social Media Safety': ['Set your profiles to private and review who can contact you.', 'Use a unique password and two-factor authentication.', 'Avoid sharing live location, OTPs, identity documents or personal details.'],
  'Online Shopping Safety': ['Use trusted stores and check the URL begins with https.', 'Avoid deals that look too good to be true.', 'Prefer secure payment methods and retain receipts.'],
  'Phishing Attacks': ['Check the sender and full URL, not just the display name.', 'Avoid links that create urgency or ask for secrets.', 'Report suspicious messages and delete them.'],
  'UPI & Banking Safety': ['Never share your OTP, UPI PIN, card PIN or CVV.', 'To receive money, do not scan QR codes or enter a PIN.', 'Call 1930 promptly if you have been defrauded.'],
  'Gaming Scams': ['Never share game credentials or buy items from unknown sellers.', 'Be wary of free coins, hacks and reward generators.', 'Keep purchases inside the official game or app store.'],
  'Email Scams': ['Check the sender domain and hover over links first.', 'Do not download surprise attachments.', 'Use official sites directly instead of links in messages.'],
  'Password Security': ['Use a unique, long passphrase for each important account.', 'Store passwords in a trusted password manager.', 'Enable two-factor authentication and never share passwords.'],
};
const awarenessLibrary = [
  ['Phishing', Fish, 'blue'], ['OTP Scam', BadgeAlert, 'coral'], ['UPI Fraud', Landmark, 'violet'], ['QR Code Scam', QrCode, 'amber'], ['Fake Job Scam', BriefcaseBusiness, 'green'], ['Social Media Safety', Smartphone, 'teal'], ['Password Security', KeyRound, 'blue'], ['Email Security', Mail, 'coral'], ['Online Shopping Safety', ShoppingBag, 'amber'], ['Identity Theft', IdCard, 'violet']
];
const awarenessDetails = {
  'Phishing': { what:'criminals use convincing messages, websites or calls to make people reveal private information', signs:['urgent language or threats','unknown or misspelled sender addresses','shortened, mismatched or suspicious links','requests for OTPs, passwords or card data','unexpected attachments'], example:'A student receives an email that appears to be from a scholarship office. The message says the application will expire in ten minutes and asks them to log in through a link. The copied site captures the student’s password.', tips:['Open official websites by typing the address yourself','Inspect the full sender address and URL','Use multi-factor authentication','Report and delete suspicious messages','Do not reuse passwords','Confirm urgent claims through an official contact number'] },
  'OTP Scam': { what:'scammers persuade victims to disclose the one-time password used to approve a login or bank transaction', signs:['a caller asks for an OTP “to verify” your account','a message promises a refund or prize','someone asks you to install screen-sharing software','unrequested login or transaction OTPs','pressure to act immediately'], example:'A caller claims to be bank support and says a debit card needs verification. They ask the customer to read an OTP aloud. The OTP actually confirms an online payment.', tips:['Never share an OTP with any person','Banks and UPI apps do not need your OTP by phone','Do not install remote-access apps for strangers','Read OTP messages before entering any code','Turn on transaction alerts','Call your bank only through its official number'] },
  'UPI Fraud': { what:'fraudsters misuse payment requests, collect links, QR codes or screen access to steal money through digital payments', signs:['request to enter a UPI PIN to receive money','unknown collect request','QR code sent as a “refund”','screen sharing request','offer that requires advance payment'], example:'A seller says they will refund a student for a cancelled order. Instead of sending money, they send a collect request. The student enters a PIN and the amount is debited.', tips:['A UPI PIN is only for sending money','Reject unknown collect requests','Never scan a QR code to receive money','Verify the recipient before paying','Set low transaction limits','Call 1930 quickly if money is lost'] },
  'QR Code Scam': { what:'attackers use QR codes that open payment requests, phishing pages or malicious downloads', signs:['QR code offered to receive a payment','code pasted over a genuine poster','unverified code in a chat or social post','instruction to scan before a refund','QR link asking for banking details'], example:'A customer trying to sell an old phone receives a buyer’s QR code. After scanning it, the buyer asks for a PIN. The PIN approves payment from the seller’s own account.', tips:['Scan QR codes only from trusted sources','Do not scan to receive money','Check the app screen before approving any action','Use your payment app directly for refunds','Avoid QR codes sent by unknown contacts','Report tampered codes to the business'] },
  'Fake Job Scam': { what:'fraudsters offer attractive jobs or internships to collect money, documents or personal data', signs:['guaranteed job without interview','request for registration or training fees','unofficial email domains','salary that seems unrealistic','pressure to share Aadhaar, PAN or bank details'], example:'A student sees a work-from-home listing with a high daily income. After being selected instantly, they are asked to pay a “verification fee” and submit identity documents.', tips:['Research the company on its official site','Never pay to obtain a job','Use trusted job platforms','Verify recruiter email domains','Do not share documents until an employer is verified','Discuss suspicious offers with a placement cell'] },
  'Social Media Safety': { what:'safe practices that reduce account takeover, impersonation, stalking and privacy risks on social networks', signs:['unexpected password-reset messages','new login notifications','fake profiles using your photo','requests for OTPs or money from friends','unknown links in direct messages'], example:'A cloned profile uses a student’s public photos and sends messages to classmates asking for urgent money. The scam succeeds because people trust the familiar picture.', tips:['Use private-profile controls where appropriate','Enable two-factor authentication','Review linked devices and login sessions','Limit personal information in public posts','Verify money requests through a call','Report impersonation quickly'] },
  'Password Security': { what:'the practice of creating and protecting credentials so that one compromised account does not expose all others', signs:['password reused on many sites','browser warning about a leaked password','unknown login alerts','very short or predictable password','sharing passwords in chat'], example:'A password leaked from an old shopping site is reused for email. Attackers try the same email-password combination and gain access to the more important mailbox.', tips:['Use a unique passphrase for each account','Choose at least 14 characters','Use a trusted password manager','Enable two-factor authentication','Change passwords after a confirmed breach','Never share credentials'] },
  'Email Security': { what:'methods for checking senders, links, attachments and account settings before trusting an email', signs:['display name does not match email domain','grammar errors or unusual tone','unexpected attachment','urgent payment request','link destination differs from visible text'], example:'A message appears to be from a college administrator and asks students to open a timetable attachment. The attachment instead installs malicious software.', tips:['Verify the complete sender address','Hover over links before opening them','Do not open unexpected attachments','Use spam reporting tools','Keep email recovery details current','Enable two-factor authentication'] },
  'Online Shopping Safety': { what:'careful habits that help buyers avoid fake stores, counterfeit products and payment fraud', signs:['unrealistic discounts','new store without contact details','payment requested outside the platform','only prepaid options','copied product images and reviews'], example:'A social-media shop advertises branded headphones at a very low price. After payment, the page disappears and the buyer has no order confirmation or support contact.', tips:['Use established stores or marketplaces','Check HTTPS and contact details','Read independent reviews','Avoid direct-bank-transfer requests','Keep order confirmations','Use secure payment methods'] },
  'Identity Theft': { what:'the misuse of personal data or documents to impersonate someone, open accounts or carry out fraud', signs:['unknown accounts or transactions','unexpected credit enquiries','requests for identity documents without reason','lost documents or suspicious copies','unfamiliar recovery email or phone number'], example:'A document image shared for an unverified rental listing is reused to create a financial account. The victim discovers it only after receiving unexpected account messages.', tips:['Share masked documents whenever possible','Add a purpose and date watermark to copies','Avoid sending identity documents through casual chat','Secure mail and cloud accounts','Review financial statements','Report lost documents and identity misuse quickly'] }
};

function Logo({ light = false }) { return <a className={`logo ${light ? 'light' : ''}`} href="#/home"><span className="logo-mark"><ShieldCheck size={26}/></span><span><small>STUDENT COMMUNITY</small><strong>CYBER SAFETY</strong><em>HELP DESK</em></span></a> }
function Nav({ page, setMenu }) { const logged=Boolean(localStorage.getItem('cyberUser')); const links = [['home','Home'], ['awareness','Awareness'], ['assistant','AI Assistant'], ['alerts','Scam Alerts'], ['report','Report Scam'], ['resources','Resources'], ['contact','Contact']]; const logout=()=>{localStorage.removeItem('cyberUser');setMenu(false);window.location.hash='/login'}; return <nav className="nav">{links.map(([id, label]) => <a onClick={()=>setMenu(false)} className={page === id ? 'active' : ''} href={`#/${id}`} key={id}>{label}</a>)}{logged?<button className="login-link logout" onClick={logout}><LogOut size={17}/> Logout</button>:<a className="login-link" href="#/login"><User size={17}/> Login</a>}</nav> }
function Header({ page }) { const [menu, setMenu] = useState(false); return <header><div className="shell nav-shell"><Logo light/><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu ? <X/>:<Menu/>}</button><div className={menu ? 'nav-open' : ''}><Nav page={page} setMenu={setMenu}/></div></div></header> }
function Hero() { const [query,setQuery]=useState(''); const search=e=>{e.preventDefault();if(query.trim()) window.location.hash=`#/resources?search=${encodeURIComponent(query.trim())}`}; return <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">COMMUNITY</p><h1>CYBER <span>SAFETY</span><br/><i>HELP DESK</i></h1><h2>Stay Safe. Stay Aware.<br/><b>We Are Here to Help.</b></h2><p className="lead">Your student-first space for cyber safety guidance, scam awareness and trusted support.</p><form className="search" onSubmit={search}><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cyber safety resources..."/><button type="submit">Search</button></form><a className="primary" href="#/assistant"><Bot size={20}/> Ask AI Assistant <ArrowRight size={19}/></a><p className="under">Search guides or get instant help from the AI Assistant.</p></div><HeroArt/><aside className="daily-tip"><Zap size={23}/><div><b>Daily Cyber Safety Tip</b><p>Never share your OTP, password or banking PIN with anyone.</p></div></aside></div></section> }
function HeroArt(){ return <div className="hero-art"><div className="glow"></div><div className="monitor"><div className="circuit">⌁ ⌁ ⌁</div><ShieldCheck size={100}/><span>YOUR SAFETY<br/>OUR PRIORITY</span></div><div className="desk"></div><div className="laptop"><Lock/><span></span></div><div className="shield-float"><ShieldCheck size={70}/></div><div className="person"><div></div><i></i></div></div> }
function Topics(){ return <section className="section topics"><div className="shell"><div className="section-head"><p className="eyebrow">LEARN & PROTECT</p><h2>Cyber safety, made <span>simple.</span></h2></div><div className="topic-grid">{topics.map(({title,text,icon:Icon,tone})=><article className="topic-card" key={title}><span className={`round ${tone}`}><Icon/></span><div><h3>{title}</h3><p>{text}</p><a href="#/awareness">Explore <ChevronRight size={15}/></a></div></article>)}</div></div></section> }
function Info(){return <section className="section info"><div className="shell info-grid"><article className="info-card alerts"><div className="card-title"><TriangleAlert/> <h3>Latest Scam Alerts</h3><a href="#/awareness">View all</a></div>{['Fake Internship Messages','QR Code Scam','Fake Scholarship Website','WhatsApp OTP Scam'].map((x,i)=><p key={x}><span>●</span>{x}<time>{[2,5,1,2][i]} {i<2?'hrs':'day'} ago</time></p>)}</article><article className="info-card help"><div className="card-title"><Headphones/> <h3>Need Help?</h3></div><p><span>›</span>Cyber Crime Helpline <b>1930</b></p><p><span>›</span>Report Online Fraud <a href="#/report">Report now</a></p><p><span>›</span>National Cyber Crime Portal <a href="https://cybercrime.gov.in" target="_blank">Visit portal</a></p><p><span>›</span>Emergency Contacts <a href="#/contact">View all</a></p></article><article className="info-card why"><div className="card-title"><ShieldCheck/> <h3>Why Cyber Safety?</h3></div><p>Cyber crimes are increasing every day. Stay informed, alert and protect yourself and others from online frauds and cyber threats.</p><a className="small-btn" href="#/awareness">Learn More</a></article></div></section>}
function Footer(){return <footer><div className="shell footer"><Logo light/><p>© 2026 Student Community Cyber Safety Help Desk.</p><div className="foot-links"><a href="#/privacy">Privacy Policy</a><a href="#/terms">Terms & Conditions</a><a href="#/contact">Contact Support</a></div><div className="social" aria-label="Social media"><b>f</b><b>◎</b><MessageCircle/><b>▶</b></div></div></footer>}
function Counter({end,label,Icon}){const [n,setN]=useState(0);useEffect(()=>{let x=0;const t=setInterval(()=>{x+=Math.ceil(end/30);if(x>=end){x=end;clearInterval(t)}setN(x)},30);return()=>clearInterval(t)},[end]);return <article className="counter"><Icon/><strong>{n}{end===1930?'': '+'}</strong><span>{label}</span></article>}
function Stats(){return <section className="stats"><div className="shell stats-grid"><Counter end={1930} label="Cyber Helpline" Icon={Phone}/><Counter end={24} label="Portal Support" Icon={ShieldCheck}/><Counter end={60} label="Awareness Tips" Icon={Sparkles}/><Counter end={12} label="Safe Browsing Guides" Icon={Search}/></div></section>}
function Emergency(){return <section className="emergency"><div className="shell emergency-inner"><div><p className="eyebrow">NEED URGENT HELP?</p><h2>Act fast. Report safely.</h2><p>If money was lost in an online scam, call the cyber helpline immediately.</p></div><div><a className="emergency-call" href="tel:1930"><Phone/> Call 1930</a><a href="https://cybercrime.gov.in" target="_blank" rel="noreferrer">National Portal</a><a href="https://www.cert-in.org.in" target="_blank" rel="noreferrer">CERT-In</a><a href="https://www.rbi.org.in" target="_blank" rel="noreferrer">RBI Tips</a></div></div></section>}
function Alerts(){const items=[['Fake KYC Scam','Fraudsters impersonate banks and ask for OTPs.','High'],['QR Code Scam','Never scan a QR code to receive money.','High'],['WhatsApp Scam','Verify urgent requests from unknown contacts.','Medium'],['Job Scam','Never pay registration fees for a job.','Medium'],['UPI Fraud','Never share your UPI PIN or screen access.','High']];return <Inner title="Latest Scam Alerts"><p className="page-lead">Recognise common scams before they exploit your money or identity.</p><div className="alert-grid">{items.map(([t,d,l])=><article className="alert-item" key={t}><AlertTriangle/><div><em>{l} risk</em><h3>{t}</h3><p>{d}</p><a href="#/report">Report this scam <ArrowRight size={15}/></a></div></article>)}</div></Inner>}
function Dashboard(){const name=(localStorage.getItem('cyberUser')||'Student').split('@')[0];return <Inner page="home" title={`Welcome back, ${name}.`}><p className="page-lead">Your Cyber Safety Dashboard gives you immediate actions and current awareness alerts.</p><div className="dashboard"><section><h2>Quick Actions</h2><div className="quick-actions"><a href="#/assistant"><Bot/>Ask AI Assistant</a><a href="#/report"><ShieldCheck/>Report a Scam</a><a href="#/alerts"><AlertTriangle/>View Scam Alerts</a></div><h2>Recent Scam Alerts</h2><div className="dash-alert"><AlertTriangle/><span><b>Fake KYC Scam</b><small>Never disclose OTPs to callers.</small></span><em>High</em></div><div className="dash-alert"><AlertTriangle/><span><b>UPI Fraud</b><small>You never enter a PIN to receive money.</small></span><em>High</em></div><h2>Recent Activity</h2><div className="dash-alert"><TimerReset/><span><b>Safety guide viewed</b><small>Phishing awareness guide added to your learning journey.</small></span><em>Today</em></div></section><aside className="safety-score"><ShieldCheck/><p>YOUR SAFETY SCORE</p><strong>82%</strong><span>Enable two-factor authentication to improve your score.</span><a href="#/awareness">Improve safety <ArrowRight size={15}/></a><div className="dashboard-ai"><Bot/> AI Assistant is ready for cyber-safety questions.</div><a className="helpline" href="tel:1930"><Phone/> Emergency Helpline 1930</a></aside></div></Inner>}
function Home(){return <><Header page="home"/><Hero/><div className="safety-ticker"><AlertTriangle/> Beware of Fake KYC Calls — banks never ask for OTPs or PINs. <span>•</span> Verify before you trust.</div><Topics/><Info/><Stats/><Emergency/><Footer/></>}
function Inner({page, title,children}){return <><Header page={page}/><main className="inner"><div className="shell"><p className="eyebrow">STUDENT CYBER SAFETY HUB</p><h1>{title}</h1>{children}</div></main><Footer/></>}
function Awareness(){return <Inner page="awareness" title="Cyber Awareness Library"><p className="page-lead">In-depth, student-friendly learning pages on the scams and digital habits that matter most. Open a topic to read a complete awareness guide.</p><div className="resource-grid">{awarenessLibrary.map(([title,Icon,tone])=><article className="resource-card" key={title}><span className={`round ${tone}`}><Icon/></span><h3>{title}</h3><p>Learn how this threat works, its warning signs, practical prevention and a concise safety checklist.</p><a className="card-action" href={`#/awareness/${encodeURIComponent(title)}`}>Read full guide <ArrowRight size={16}/></a></article>)}</div></Inner>}
function Resources(){const search=new URLSearchParams(location.hash.split('?')[1]||'').get('search')||'';const shown=resources.filter(([title,text])=>`${title} ${text}`.toLowerCase().includes(search.toLowerCase()));return <Inner title="Your cyber safety toolkit."><p className="page-lead">Save these practical resources and make every digital moment safer.</p>{search&&<p className="search-status">{shown.length ? `Showing ${shown.length} result(s) for “${search}”.` : `No resource found for “${search}”. Try password, phishing, UPI or social media.`}</p>}<div className="resource-grid">{shown.map(([title,text,Icon])=><article className="resource-card" key={title}><span className="round blue"><Icon/></span><h3>{title}</h3><p>{text}</p><a className="card-action" href={`#/guide/${encodeURIComponent(title)}`}>Read resource <ArrowRight size={16}/></a></article>)}</div></Inner>}
function Guide({name}){const clean=decodeURIComponent(name||'');const info=awarenessDetails[clean];if(!info){const tips=guideContent[clean]||guideContent.Phishing;return <Inner title={clean||'Cyber safety guide'}><div className="guide"><h2>What you should do</h2><ol>{tips.map(tip=><li key={tip}>{tip}</li>)}</ol><a className="primary" href="#/report">Report a Scam <ArrowRight size={18}/></a></div></Inner>}const match=awarenessLibrary.find(([t])=>t===clean);const Icon=match?.[1]||ShieldCheck;return <Inner page="awareness" title={clean}><article className="long-guide"><div className="guide-hero"><span className={`round ${match?.[2]||'blue'}`}><Icon/></span><div><p className="eyebrow">COMPLETE AWARENESS GUIDE</p><h2>Understand, identify and prevent {clean.toLowerCase()}.</h2></div></div><section><h3>Introduction</h3><p>{clean} is a cyber-safety issue that affects students, families and first-time digital users because {info.what}. Criminals depend less on advanced technology than on trust, urgency and confusion. Knowing the basic pattern helps a person pause before making a decision that could expose money, personal information or an online account.</p><h3>How it works</h3><p>Most incidents start with a convincing trigger: a message, phone call, social-media post, website, payment request or unexpected offer. The attacker makes the situation appear urgent or beneficial, then asks the victim to click, share, pay, scan or install something. Once a victim acts, the criminal may capture credentials, approve a transaction, take over an account or collect identity data. The safest response is to stop, independently verify the request and use official channels.</p><h3>Warning signs</h3><ul>{info.signs.map(x=><li key={x}>{x}</li>)}</ul><h3>Real-life example</h3><p>{info.example}</p><h3>Prevention tips</h3><ol>{info.tips.map(x=><li key={x}>{x}</li>)}</ol><h3>Do’s and Don’ts</h3><div className="dos"><div><b>Do</b><p>Pause when a message creates pressure. Verify the person or organisation with an official website, known phone number or trusted adult. Keep evidence such as screenshots, transaction IDs and phone numbers if something feels suspicious.</p></div><div><b>Don’t</b><p>Do not share OTPs, passwords, UPI PINs, CVVs or screen access. Do not pay fees to unlock rewards, refunds or jobs. Do not trust a logo, profile picture or display name without checking the source.</p></div></div><h3>Quick summary</h3><p>{clean} becomes far less effective when you slow down, verify independently and protect private information. If money is lost, contact the Cyber Helpline at <b>1930</b> immediately and submit an official complaint at the National Cyber Crime Portal.</p></section><a className="primary" href="#/awareness">← Back to Awareness</a></article></Inner>}
function Report(){const [state,setState]=useState('idle');const formRef=useRef();const submit=e=>{e.preventDefault();setState('loading');setTimeout(()=>{formRef.current?.reset();setState('sent')},850)};return <Inner page="report" title="Report a scam safely."><div className="form-wrap"><div><h2>Tell us what happened</h2><p>Your details are used only to help guide you towards the right next step. If money was lost, call <b>1930</b> immediately.</p><div className="callout"><Headphones/> Cyber Crime Helpline <strong>1930</strong></div></div><form ref={formRef} onSubmit={submit}>{state==='sent'?<div className="success"><CheckCircle2 size={42}/><h3>Report received</h3><p>Your form has been cleared. Keep screenshots and transaction evidence, then call 1930 for urgent financial fraud.</p><button className="primary" type="button" onClick={()=>setState('idle')}>Submit another report</button></div>:<><label>Name<input required placeholder="Your full name"/></label><label>Mobile Number<input required type="tel" pattern="[0-9]{10}" placeholder="10-digit mobile number"/></label><label>Scam Type<select required defaultValue=""><option value="" disabled>Select scam type</option><option>UPI / Banking fraud</option><option>OTP Scam</option><option>QR Code Scam</option><option>Fake Job Scam</option><option>Social media scam</option><option>Other</option></select></label><label>Date<input required type="date"/></label><label className="full">Description<textarea required placeholder="Describe what happened, without sharing passwords or OTPs."></textarea></label><div className="form-buttons"><button className="primary" disabled={state==='loading'} type="submit">{state==='loading'?'Submitting…':'Submit Report'} <Send size={18}/></button><button type="button" className="clear-button" onClick={()=>formRef.current?.reset()}>Clear form</button></div></>}</form></div></Inner>}
function Assistant(){const [messages,setMessages]=useState([{role:'bot',text:'Hi! I am your Cyber Safety Assistant. Ask me about phishing, passwords, UPI, social media safety, scams, or reporting cybercrime.'}]);const [value,setValue]=useState('');const [typing,setTyping]=useState(false);const end=useRef();useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages,typing]);const answer=q=>{const s=q.toLowerCase();if(!/(cyber|scam|phish|password|upi|bank|otp|safe|fraud|email|social|hack|online|security)/.test(s))return 'I can only help with cyber safety and online security questions. Try asking about phishing, passwords, UPI fraud, or reporting a scam.';if(/otp|upi|bank/.test(s))return 'Never share your OTP, UPI PIN, CVV, or screen-sharing access. To receive money, you never need to enter a PIN. If money was lost, call 1930 immediately.';if(/phish|email|link/.test(s))return 'Phishing uses a fake message or site to steal information. Check sender addresses and full URLs, do not open unexpected attachments, and verify urgent requests through official contacts.';if(/password/.test(s))return 'Use a unique 14+ character passphrase for every important account and enable two-factor authentication. A password manager makes this much easier.';return 'Stay safe online by verifying messages, keeping software updated, using unique passwords and two-factor authentication, and never sharing OTPs or PINs.'};const submit=e=>{e?.preventDefault();const q=value.trim();if(!q||typing)return;setMessages(m=>[...m,{role:'user',text:q}]);setValue('');setTyping(true);setTimeout(()=>{setMessages(m=>[...m,{role:'bot',text:answer(q)}]);setTyping(false)},650)};const suggestions=['How do I report a UPI scam?','What is phishing?','What should I do after sharing my OTP?','How can I stay safe online?'];return <Inner page="assistant" title="AI Cyber Safety Assistant"><div className="chat"><div className="chat-top"><Bot/><div><b>Cyber Safety Assistant</b><small><i/> Online · Safety questions only</small></div></div><div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.role==='bot'&&<Bot size={17}/>}<p>{m.text}</p></div>)}{typing&&<div className="message bot typing"><Bot size={17}/><p><i/><i/><i/></p></div>}<div ref={end}/></div><div className="suggestions">{suggestions.map(q=><button key={q} onClick={()=>setValue(q)}>{q}</button>)}</div><form className="chat-form" onSubmit={submit}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Ask a cyber safety question..."/><button aria-label="Send"><Send size={20}/></button></form></div></Inner>}
function Contact(){return <Inner title="We are here to help."><div className="contact-grid"><article><Headphones/><h2>Immediate fraud support</h2><p>If you have lost money to a cyber fraud, call the National Cyber Crime Helpline as soon as possible.</p><strong>1930</strong></article><article><Mail/><h2>Support desk</h2><p>For campus awareness requests or general assistance, write to our community support team.</p><a href="mailto:support@cybersafety.edu">support@cybersafety.edu</a></article></div></Inner>}
function Login(){const [show,setShow]=useState(false);const [mode,setMode]=useState('login');const [notice,setNotice]=useState('');const title=mode==='login'?'Welcome Back!':mode==='register'?'Create your account':'Reset your password';const submit=e=>{e.preventDefault();const data=new FormData(e.currentTarget);if(mode==='forgot'){setNotice(`A password-reset link would be sent to ${data.get('email')}. (Demo mode)`);return}if(mode==='register'){setNotice('Account created successfully. You can now log in.');setMode('login');return}localStorage.setItem('cyberUser',data.get('email'));window.location.hash='/dashboard'};return <main className="login-page"><section className="login-brand"><Logo light/><div className="brand-copy"><p className="eyebrow">STUDENT COMMUNITY</p><h1>Stay Safe. Stay Aware.<br/><span>We Are Here to Help.</span></h1><p>Your trusted platform for cyber safety guidance, awareness and reporting cyber crimes.</p></div><HeroArt/><div className="trust"><span><ShieldCheck/>100% Secure<small>Your data is safe with us.</small></span><span><Bot/>AI Powered<small>Instant answers and support.</small></span><span><User/>Trusted by<small>Students in the community.</small></span></div></section><section className="login-panel"><a className="back" href="#/home">← Back to home</a><div className="login-card"><h1>{title}</h1><p>{mode==='login'?'Login to continue to your Safety Dashboard':mode==='register'?'Join the student cyber safety community.':'Enter your email and we will help you reset your password.'}</p>{notice&&<div className="form-notice">{notice}</div>}<form onSubmit={submit}>{mode==='register'&&<label><User/><input required name="name" placeholder="Full name"/></label>}<label><User/><input required name="email" type="email" placeholder="Email address"/></label>{mode!=='forgot'&&<label><Lock/><input required name="password" type={show?'text':'password'} minLength="6" placeholder="Password"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></label>}{mode==='login'&&<div className="remember"><label><input type="checkbox"/> Remember Me</label><button type="button" className="text-btn" onClick={()=>{setNotice('');setMode('forgot')}}>Forgot Password?</button></div>}<button className="login-btn"> <Lock size={19}/>{mode==='login'?'Login':mode==='register'?'Create Account':'Send Reset Link'}</button></form>{mode==='login'&&<><div className="or"><span/>or<span/></div><button className="create" onClick={()=>{setNotice('');setMode('register')}}><User/> Create New Account</button></>}{mode!=='login'&&<button className="back-login" onClick={()=>{setNotice('');setMode('login')}}>← Back to Login</button>}<div className="safe-box"><ShieldCheck/><b>Together, let’s build a safer<br/>digital community.</b></div></div></section></main>}
function App(){const getRoute=()=>location.hash.slice(2)||'home';const [route,setRoute]=useState(getRoute);useEffect(()=>{const f=()=>setRoute(getRoute());addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const [page,guide]=route.split('?')[0].split('/');const pages={home:<Home/>,dashboard:<Dashboard/>,awareness:<Awareness/>,assistant:<Assistant/>,alerts:<Alerts/>,report:<Report/>,resources:<Resources/>,contact:<Contact/>,login:<Login/>};return page==='guide'||(page==='awareness'&&guide)?<Guide name={guide}/>:pages[page]||<Home/>}
export default App;
